### ISSUE TITLE
"execution error: Can’t get project of missing value. (-1728)" when running tuturoial app.

### ISSUE THREAD

**Issue by foxyblocks** [moredip/Frank#10]
I'm working through the tutorial and running into an error on the first When step:

```
    Feature: Drive our App using Cucumber

      Scenario: Plus Button adds timestamp                 # features/tutorial.feature:3
    129:136: execution error: Can’t get project of missing value. (-1728)

    PING FAILED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

I have a similar issue when trying to run cucumber in the example app EmployeeAdmin:

```
        129:136: execution error: Can’t get project of missing value. (-1728)
            Given the app has just started # features/step_definitions/employee_admin_steps.rb:1

          Scenario: Add test user                             # features/main.feature:6
            When I touch the Add User button                  # features/step_definitions/employee_admin_steps.rb:5
              Connection refused - connect(2) (Errno::ECONNREFUSED)
              /Volumes/MacintoshHD/Users/christian/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/net/http.rb:560:in `initialize'
              /Volumes/MacintoshHD/Users/christian/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/net/http.rb:560:in `open'
              /Volumes/MacintoshHD/Users/christian/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/net/http.rb:560:in `connect'
              /Volumes/MacintoshHD/Users/christian/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/timeout.rb:53:in `timeout'
              /Volumes/MacintoshHD/Users/christian/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/timeout.rb:101:in `timeout'
              /Volumes/MacintoshHD/Users/christian/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/net/http.rb:560:in `connect'
              /Volumes/MacintoshHD/Users/christian/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/net/http.rb:553:in `do_start'
              /Volumes/MacintoshHD/Users/christian/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/net/http.rb:542:in `start'
              ../../cucumber/frank_helper.rb:143:in `make_http_request'
              ../../cucumber/frank_helper.rb:125:in `post_to_uispec_server'
              ../../cucumber/frank_helper.rb:60:in `frankly_map'
              ../../cucumber/frank_helper.rb:7:in `touch'
              ./features/step_definitions/employee_admin_steps.rb:6:in `/^I touch the Add User button$/'
              features/main.feature:7:in `When I touch the Add User button'
```

I'm running xcode4 GM. Could that be causing the problem?

**Comment by moredip** [comment]
I'd suggest posting this on the frank-discuss group to get more help - groups.google.com/group/frank-discuss.

The first problem may be because XCode isn't running, or you are using Spaces and XCode is running in a different Space.

The second problem seems to indicate that either the iOS app isn't running, or it doesn't have Frank's embedded http server built in and launched.

**Comment by moredip** [comment]
Looks like the technique we used to use to launch the app in the sim (using applescript) no longer works with XCode 4. We've move to using a cleaner approach using sim_launcher

**Comment by foxyblocks** [comment]
It also sucks that they removed user scripts from xcode 4, I had a good one that took a variable defined in a class interface and automatically wrote the property, synthesize, and dealloc stuff for it.
