### ISSUE TITLE
rescue EOFError fails to suppress error thrown by frank_server.send_get('exit')

### ISSUE THREAD

**Issue by imvjhere** [moredip/Frank#190]
We dont have the uispec_server running during frank test, so it is not possible to call get_to_uispec_server

But instead I tried calling the 

frank_server.send_get('exit')

This clean exits and the iOS app, but, "rescue EOFError" doesn't seem to be working. Hence I get failure error message all the time. 

I even tried to try catch the exit event, by doing the following

def frankly_exit
  begin
  frank_server.send_get('exit')
  # get_to_uispec_server('exit')
  # calling exit in the app will not return any response
  # so we simply catch the error caused by exiting.
  rescue EOFError
  end
end

But still it returns error saying 

```
   (Frank::Cucumber::FrankNetworkError)
  /Library/Ruby/Gems/1.8/gems/frank-cucumber-0.9.6/lib/frank-cucumber/gateway.rb:91:in `make_http_request'
  /Library/Ruby/Gems/1.8/gems/frank-cucumber-0.9.6/lib/frank-cucumber/gateway.rb:68:in `send_get'
  ./step_definitions/hooks.rb:21:in `frankly_exit'
  ./step_definitions/hooks.rb:16:in `After'
```

Any solution / suggestion ?

**Comment by ondrejhanslik** [comment]
`(Frank::Cucumber::FrankNetworkError)`

you can use `FrankNetworkError`, `RuntimeError` or `Exception`.
However, I think that `frankly_exit` should be added to `FrankHelper` because it's very useful.
