### ISSUE TITLE
libtool: unknown option character `W' in: -Wl,-no_compact_unwind

### ISSUE THREAD

**Issue by alhafoudh** [moredip/Frank#192]
I get this error when trying to get Frank and cocoapods to work.

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `W' in: -Wl,-no_compact_unwind
```

More log:

```
 Libtool /Users/username/Library/Developer/Xcode/DerivedData/app1-awcrckypdaygydaiioqtlgkerbvf/Build/Intermediates/UninstalledProducts/libPods.a normal i386
    cd /Users/username/Projects/dir1/app1/Pods
    setenv IPHONEOS_DEPLOYMENT_TARGET 5.0
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/bin:/Users/username/.rbenv/versions/1.9.3-p385/bin:/usr/local/Cellar/rbenv/0.4.0/libexec:/Users/username/.rbenv/shims:/usr/local/share/npm/bin:/usr/local/sbin:/Users/username/.dotfiles/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only i386 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk -L/Users/username/Library/Developer/Xcode/DerivedData/app1-awcrckypdaygydaiioqtlgkerbvf/Build/Products/Debug-iphonesimulator -L/Users/username/Projects/dir1/app1/Pods/Pods/TestFlightSDK -filelist /Users/username/Library/Developer/Xcode/DerivedData/app1-awcrckypdaygydaiioqtlgkerbvf/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods.build/Objects-normal/i386/Pods.LinkFileList -ObjC -Wl,-no_compact_unwind -lTestFlight -lz -framework CoreData -framework MessageUI -framework UIKit -framework Foundation -o /Users/username/Library/Developer/Xcode/DerivedData/app1-awcrckypdaygydaiioqtlgkerbvf/Build/Intermediates/UninstalledProducts/libPods.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `W' in: -Wl,-no_compact_unwind
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool failed with exit code 1


** BUILD FAILED **


The following build commands failed:
  Libtool /Users/username/Library/Developer/Xcode/DerivedData/app1-awcrckypdaygydaiioqtlgkerbvf/Build/Intermediates/UninstalledProducts/libPods.a normal i386
(1 failure)
/Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/fileutils.rb:1344:in `mkdir': No such file or directory - /Users/username/Projects/dir1/app1/Frank/frankified_build/Frankified.app (Errno::ENOENT)
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/fileutils.rb:1344:in `copy'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/fileutils.rb:465:in `block in copy_entry'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/fileutils.rb:1433:in `preorder_traverse'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/fileutils.rb:462:in `copy_entry'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/fileutils.rb:437:in `block in cp_r'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/fileutils.rb:436:in `cp_r'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/frank-cucumber-1.1.8/lib/frank-cucumber/cli.rb:111:in `build'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
  from /Users/username/.rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/frank-cucumber-1.1.8/bin/frank:5:in `<top (required)>'
  from /Users/username/.rbenv/versions/1.9.3-p385/bin/frank:23:in `load'
  from /Users/username/.rbenv/versions/1.9.3-p385/bin/frank:23:in `<main>'
```

**Comment by moredip** [comment]
Could you please report this on the Frank mailing list. You have more of a chance of getting help there.

Cheers,

## Pete

Typed on a little bitty keyboard

**Comment by alhafoudh** [comment]
Hi,
shure I can :) I just did.

BR

## 

Ahmed Al Hafoudh
CEO

Mobile: +421 918 341 216
Email: alhafoudh@freevision.sk
Web: www.freevision.sk

**Comment by alhafoudh** [comment]
Huh, what happened?

**Comment by moredip** [comment]
I closed out this issue as I figured it was better worked out on the mailing list than here - I was spring cleaning old issues here.

To be honest I'm not sure if this is a Frank issue or a CocoaPods issue.

**Comment by iamabhiee** [comment]
I am facing the same issue, any solution?
