### ISSUE TITLE
Frankified app can't launch after build

### ISSUE THREAD

**Issue by chouti** [moredip/Frank#198]
Before build I've removed the "-all_load" FRANK_LDFLAGS, in order to avoid the duplicate symbol issue

after build succeeded I've got below error message

```
** BUILD SUCCEEDED **

/Users/emon/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/1.9.1/fileutils.rb:1357:in `copy': cannot handle socket (RuntimeError)
    from /Users/emon/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/1.9.1/fileutils.rb:465:in `block in copy_entry'
    from /Users/emon/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/1.9.1/fileutils.rb:1433:in `preorder_traverse'
    from /Users/emon/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/1.9.1/fileutils.rb:462:in `copy_entry'
    from /Users/emon/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/1.9.1/fileutils.rb:437:in `block in cp_r'
    from /Users/emon/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
    from /Users/emon/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
    from /Users/emon/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
    from /Users/emon/.rvm/rubies/ruby-1.9.3-rc1/lib/ruby/1.9.1/fileutils.rb:436:in `cp_r'
    from /Users/emon/.rvm/gems/ruby-1.9.3-rc1@rails3.2/gems/frank-cucumber-1.1.10/lib/frank-cucumber/cli.rb:115:in `build'
    from /Users/emon/.rvm/gems/ruby-1.9.3-rc1@rails3.2/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/emon/.rvm/gems/ruby-1.9.3-rc1@rails3.2/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/emon/.rvm/gems/ruby-1.9.3-rc1@rails3.2/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/emon/.rvm/gems/ruby-1.9.3-rc1@rails3.2/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/emon/.rvm/gems/ruby-1.9.3-rc1@rails3.2/gems/frank-cucumber-1.1.10/bin/frank:5:in `<top (required)>'
    from /Users/emon/.rvm/gems/ruby-1.9.3-rc1@rails3.2/bin/frank:19:in `load'
    from /Users/emon/.rvm/gems/ruby-1.9.3-rc1@rails3.2/bin/frank:19:in `<main>'
```

And my frankified app can't be launched with `frank launch`

**Comment by moredip** [comment]
That's a strange error. It [looks like](https://github.com/moredip/Frank/blob/master/gem/lib/frank-cucumber/cli.rb#L115) it's happening when the frank build is trying to copy the Frankified app into the new directory. I don't suppose your machine's disk is full?

Can you share the full output of the build to help me diagnose this.

**Comment by chouti** [comment]
@moredip Yep, my disk has enough free space.

And I thought this issue mostly like wrong FRANK_LDFLAGS here, I've tried several different LDFLAGS and finally got this build finished successfully.

https://gist.github.com/chouti/5453155 This is the out put while build successfully.

**BUT** when I try `frank launch` after that, I can get my simulator up and running, when I try `frank inspect`, I can't open http://localhost:37265 in Safari

https://gist.github.com/chouti/5453164 here is the out put when I tried `curl -vv http://localhost:37265`

I've no idea why the http sever was not start.

**Comment by moredip** [comment]
I'm at a bit of a loss on this one. Is there any chance you could share your repo with me so I can help get to the bottom of this?

**Comment by Palleas** [comment]
I'm having the same issue right now, any news ?

**Comment by dlongmuir** [comment]
I was seeing that until I switched to use "Debug" configuration for command line builds. I also build for frank using:

frank build --workspace Project.xcworkspace --scheme Project --configuration ONLY_ACTIVE_ARCH=NO

**Comment by alexnauda** [comment]
I'm getting this error too, using frank-cucumber-1.2.2 on mac ruby 1.8 (and bundler). Adding the configuration parameter to frank build didn't help.  @dlongmuir How can I make sure 'frank build' is using the "Debug" configuration for command line builds?

**Comment by alexnauda** [comment]
And (oh right) I forgot to mention that I'm using Cocoapods. After reading this [related discussion](https://groups.google.com/forum/#!topic/frank-discuss/98Tt6-eJ3x0) I noticed that, after running 'frank build', my app is in ./Frank/frankified_build/Applications/ instead of ./Frank/frankified_build/. I did this a579fd8cfe75433fbfbea147f164d6a6d21d01d8 and now the whole process seems to be working.
