### ISSUE TITLE
Running cucumber fails with "jQuery is not defined (V8::JSError)"

### ISSUE THREAD

**Issue by brodo** [moredip/Frank#71]
Hi, 
i just installed Frank on Mac OS X Lion and when i try to run cucumber i get the following error:

```
schle/% cucumber                                                                                                                                                                        ~/Workspace/bikar
jQuery is not defined (V8::JSError)
at ./Frank/frank_static_resources.bundle/jquery-ui.min.js:10:1
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/../lib/cucumber/js_support/js_language.rb:28:in `send'
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/../lib/cucumber/js_support/js_language.rb:28:in `method_missing'
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/../lib/cucumber/js_support/js_language.rb:118:in `load_code_file'
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/../lib/cucumber/runtime/support_code.rb:171:in `load_file'
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/../lib/cucumber/runtime/support_code.rb:83:in `load_files!'
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/../lib/cucumber/runtime/support_code.rb:82:in `each'
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/../lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/../lib/cucumber/runtime.rb:174:in `load_step_definitions'
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/../lib/cucumber/runtime.rb:40:in `run!'
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/../lib/cucumber/cli/main.rb:43:in `execute!'
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/../lib/cucumber/cli/main.rb:20:in `execute'
/Library/Ruby/Gems/1.8/gems/cucumber-1.1.4/bin/cucumber:14
/usr/bin/cucumber:19:in `load'
/usr/bin/cucumber:19
```

**Comment by brodo** [comment]
Found the issue. The tutorial says:

> Run the cucumber command from your project directory.

But you have to run them from the Frank subdirectory.

**Comment by moredip** [comment]
Not sure what is going on here, but it looks like cucumber is trying to evaluate some of the JavaScript code that Frank bundles with it to allow easier inspection of the app UI. Can you post a directory listing showing where you are running the cucumber command from?

Cheers,

## Pete

Typed on a little bitty keyboard
